version: '3.8'

services:
  postgres:
    image: postgres:10.9
    container_name: postgres_10_9
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: gestao_produto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network: